### ISSUE TITLE
Expose more metrics in the web reports

### ISSUE THREAD

**Issue by anp** [anp/lolbench#18]
Examples of data we collect but are not exposed anywhere:

* confidence levels for the point estimates we use from criteron (eg error bars)
* other stats from criterion (outlier count within a given sample, mean, quartiles, etc)
* perf_events metrics about individual caches, faults, etc

**Comment by shssoichiro** [comment]
I can add some nice metrics to the graphs, with the stipulation that I'd like to swap the charting library to Highcharts. It has more features than Chart.js which would make adding some of these items, like the error bars, much easier.

Question: How does one go about testing the generation of the site? Just by running the docker-compose script?

**Comment by anp** [comment]
That would be great! I am apprehensive about taking on Highcharts because my experience with its performance has been poor in the past. Perhaps it's gotten better? Personally I would like to have much better load times for pages than perf.rlo currently has, and I believe it's using highcharts as well?

I agree that chart.js is limiting, and I'm not really that attached to the current site generation, but I'd like the pages to load very quickly. Seems like appropriate window dressing for tracking benchmarks :). I'd honestly love to get even faster than chart.js currently loads -- maybe there's a way to pre-render the graphs and bake them into the HTML so that the JS is only needed to highlight datapoints?

**Comment by anp** [comment]
Also, I build the website by pulling down https://github.com/anp/lolbench-data and running this command: https://github.com/anp/lolbench/blob/master/.cargo/config#L12.

**Comment by shssoichiro** [comment]
I am finding that the performance of Highcharts for these charts is actually superior to that of Chart.js, although they both load sufficiently quickly that any lag is not noticeable unless you're actively watching for it. I think pre-rendering would be cool, but I'm not sure if there's an easy way to do so. I can do some research to find out.

**Comment by shssoichiro** [comment]
I haven't found any pre-render type of workflow, but I did find that disabling animation on render gives a nice performance boost.

I have something like this so far. Let me know what else you'd like to see added.

![screenshot_20181004_195441](https://user-images.githubusercontent.com/5951392/46509507-0e04e080-c811-11e8-8382-fd7699f1a1ea.png)

**Comment by Eh2406** [comment]
> Let me know what else you'd like to see added.

If we can get the error bars for each estimate that would be lovely!

**Comment by shssoichiro** [comment]
Yes, the green is the confidence interval. It does take up most of the chart in most cases, because we have the y-axis set not to start at 0. I also think starting at 0 isn't necessary in this case, and actually makes it harder to see the outliers. But I'm open to suggestions to make it clearer that green = "normal behavior".

**Comment by shssoichiro** [comment]
This is what I have now for error bars:

![screen shot 2018-10-05 at 9 42 46 am](https://user-images.githubusercontent.com/5951392/46538995-61b01200-c883-11e8-9314-becbd9514158.png)

**Comment by anp** [comment]
One suggestion I'd have would be to convert the green band to a pair of dotted green lines or something similar that still makes it easy to tell when a point is outside of the band but which consumes less visual real estate?

**Comment by shssoichiro** [comment]
Agreed, this does look better.

![screenshot_20181005_195851](https://user-images.githubusercontent.com/5951392/46564990-2e986d80-c8d9-11e8-809a-1264d813dcfc.png)
