### ISSUE TITLE
add RustCrypto

### ISSUE THREAD

**Issue by anp** [anp/lolbench#45]
https://github.com/RustCrypto

`sha2`, `sha3` and one of AES crates can be a good start.

_Originally posted by @newpavlov in https://github.com/anp/lolbench/issues/1#issuecomment-426188155_

**Comment by thomwiggers** [comment]
Looking at SHA2 right now.

**Comment by anp** [comment]
I merged #53, going to give this a close for the time being. @newpavlov if you think there are other RustCrypto crates that should be included, please file new issues. Thanks!
